"""
Processing Status Constants for Document Ingestion Pipeline.
"""

DISCOVERED = "DISCOVERED"
INSPECTING = "INSPECTING"
EXTRACTING_TEXT = "EXTRACTING_TEXT"
CHUNKING = "CHUNKING"
EMBEDDING = "EMBEDDING"
INDEXING = "INDEXING"
READY = "READY"
OCR_REQUIRED = "OCR_REQUIRED"
FAILED = "FAILED"
